version: "{build}"
image: Visual Studio 2017
skip_tags: true
test: off
build_script:
  - ps: .\build.ps1 --automated=true
artifacts:
  - path: artifacts\*.nupkg
    name: NuGet Package
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
deploy:
  provider: NuGet
  api_key:
    secure: m2gRGTB4yjP1dXzEaJI1bJZe/XUQozSvsWg8/aHxA3cTf9xNljZj26vx7WBESFkB
  skip_symbols: true
  on:
    branch: master
