version: '{build}'
image: Visual Studio 2017
skip_tags: true
test: off
build_script:
- ps: .\build.ps1 --automated=true
artifacts:
- path: artifacts\*.nupkg
  name: NuGet Package
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
deploy:
  provider: NuGet
  api_key:
    secure: J3qSZm3pmCz+EhIrX94lma/MNpNU/FQn0vQVz+OKkO5mbOOTyphb45oXqsaVtWYf
  skip_symbols: true
  on:
    branch: master